---
version: "3.8"

services:
  7dtd-server:
    build: .
    #image: omicron:32000/7dtd-dedicated-server:${GIT_COMMIT_SHA1_SHORT}
    volumes:
      - type: volume # You could also bind-mount this to your local FS (see below)
        source: 7dtd-data
        target: /app/7dtd/data/Saves
        # - type: bind
        # source: /home/z/7DaysToDieData/Saves
        # target: /app/7dtd/data/Saves
    ports:
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8082:8082/tcp
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp
  7dtd-mod-server:
    image: nginx:1.19
    # command: [nginx-debug, "-g", "daemon off;"]
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./xpath_mods_src:/usr/share/nginx/html:ro
    ports:
      - 8080:80/tcp

volumes:
  7dtd-data:
