---
version: "3.8"

services:
  7dtd-server:
    build: .
    volumes:
      - type: volume # You could also bind-mount this to your local FS.
        source: 7dtd-data
        target: /zed/7dtd-data/Saves
    ports:
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8082:8082/tcp
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp
    network_mode: host

volumes:
  7dtd-data:
