---
version: "3.8"

services:
  7dtd-server:
    image: gitlab.com/farvour/7-days-to-die-docker-server:latest
    build:
      context: .
      cache_from: gitlab.com/farvour/7-days-to-die-docker-server:latest
    volumes:
      - type: volume # You could also bind-mount this to your local FS.
        source: 7dtd-data
        target: /zed/7dtd-data/Saves
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 26900:26900
    network_mode: host

volumes:
  7dtd-data:
