---
version: "3.8"

services:
  server:
    build: .
    env_file:
      - .env
    volumes:
      - type: volume # You could also bind-mount this to your local FS (see below)
        source: data
        target: /var/opt/7dtd/data/Saves
      - type: bind
        source: ./config/serveradmin.xml.values.in.override.yaml
        target: /opt/7dtd/serveradmin.xml.values.in.override.yaml
        read_only: true
      - type: bind
        source: ./config/serverconfig.xml.values.in.override.yaml
        target: /opt/7dtd/serverconfig.xml.values.in.override.yaml
        read_only: true
    ports:
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8082:8082/tcp
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp

volumes:
  data: null
