---
version: "3.8"

services:
  server:
    build: .
    #image: omicron:32000/7dtd-dedicated-server:${GIT_COMMIT_SHA1_SHORT}
    volumes:
      - type: volume # You could also bind-mount this to your local FS (see below)
        source: data
        target: /app/7dtd/data/Saves
      - type: bind
        source: ./config/serverconfig.xml.values.override.yml
        target: /app/7dtd/serverconfig.xml.values.override.yml
        read_only: true
    ports:
      - 8080:8080/tcp
      - 8081:8081/tcp
      - 8082:8082/tcp
      - 26900:26900/tcp
      - 26900:26900/udp
      - 26901:26901/udp
      - 26902:26902/udp

volumes:
  data: null
